### ISSUE TITLE
CIELAB implementation

### ISSUE THREAD

**Issue by mcstone** [mcnuttandrew/color-buddy#141]
Writing up the docs, I talk about LAB being calibrated to sRGB. If so, the implementation LAB or LAB D65?  It should be LAB D65 (and the correspondng LCH) to match sRGB

**Comment by mcnuttandrew** [comment]
We use "regular" lab right now. Colorjs.io doesn't include an LCH65 currently, so we can't adjust it

**Comment by mcstone** [comment]
Well, that's a nuisance. Will update the docs.
