### ISSUE TITLE
Share Palette feature

### ISSUE THREAD

**Issue by dv-klaus-eckelt** [mcnuttandrew/color-buddy#147]
Hi!

I tried Color buddy right after I saw the tweet and I love it. Really cool features!

Sending it to my colleagues I thought It would be great if I could directly share it with a color palette we are using, e.g.: https://color-buddy.netlify.app?name=observable4&colors=["#4269d0", "#f4bd4a", "#ff725c", "#6cc5b0"]

Similar to Viz Palette: https://projects.susielu.com/viz-palette?colors=[%22#4469cb%22,%22#a364ec%22,%22#fc7561%22,%22#edb23c%22]&backgroundColor=%22white%22&fontColor=%22black%22&mode=%22protanopia%22

**Comment by mcnuttandrew** [comment]
that's a great idea! i'll try to get to it soon!

**Comment by mcnuttandrew** [comment]
Okay addressed! Thanks for the good idea!
