### ISSUE TITLE
Managing and modifying Examples

### ISSUE THREAD

**Issue by mcstone** [mcnuttandrew/color-buddy#153]
Some possible improvements, big and small

- [x] Thumbnail => Thumbnails
- [ ] ~~Creating a view that has a subset of the examples is awkward. Suggest having the Thumbnails dropdown be checkboxes that indicate which to display.~~
- [x] Reset Modifications => Restore Defaults.  
- [x] Currently user-specified examples and configurations seem to be completely ephemeral at this point. That is, I make changes, close the window, go back to Color Buddy and none of the changes are saved.  Some way to persist (and export) the configuration would be important if people are going to seriously customize the samples.

**Comment by mcnuttandrew** [comment]
While the building subset view is a nice idea, i don't know that its necessary for now. if someone external requests it we can add it, but for now the simple all or single is sufficent
