### ISSUE TITLE
Interpolation enhancements

### ISSUE THREAD

**Issue by mcstone** [mcnuttandrew/color-buddy#155]
- [ ] ~~Sequence: Select points, interpolate, add colors. Realize I interpolated in the wrong space. Hit undo, editing pane vanishes. Can you just undo the add colors, leave the selection and the interpolation settings intact?~~
- [ ] Default interpolation space should match the current editing space (defaults now to LAB regardless)

**Comment by mcnuttandrew** [comment]
> Can you just undo the add colors, leave the selection and the interpolation settings intact?

Unfortunately no. This is generally a limitation of how we think of selection vs state. Selection is transient (doesn't make sense to undo/redo selectign something). Other tools make this choice different (figma for instance keeps everything in the undo/redo stack), but that doesn't make sense for the editing paradigm here.

**Comment by mcstone** [comment]
Actually, it can be quite valuable to undo/redo selection, especially if creating the selection is somewhat complicated. That's why most graphical editing tools include selection in the undo. I don't really see that it's all that different for the Color Buddy, though this isn't a request to make it generally so. The general jumpiness of the editing pane is the real problem, I suspect. A more annoying problem with Jeff's pretty design than I'd anticipated.

**Comment by mcnuttandrew** [comment]
While color buddy has a similar editing experience as graphics tools, it is a pretty substantially simpler tool and broadly does not have sufficiently complicated selections to warrant making the undo/redo stack kludgy. basically: i tried it and it was terrible and got in the way of expected behaviour
